

# Site settings
title: Kossuth ter - Audioguide
description: > # this means to ignore newlines until "baseurl:"
  A web-based audio guide theme for Jekyll.
baseurl: "/audioguide" # the subpath of your site, e.g. /blog
audio_path: "/audio/"
episode_hero_path: "/assets/img/stops/"
url: "https://orszaghaz.github.io"
logo: "/assets/img/logo/audio-guide.png"
menu_heading: "Válasszon másik megállót"
index_page_text: "Válasszon ki egy audioguide megállót a kezdéshez."
headphones_icon_color: "/assets/img/icons/headphones-dark.png"
headphones_icon_light: "/assets/img/icons/headphones-light.png"

# Build settings
markdown: kramdown

# Version settings (version number below is used for cache busting CSS and JS)
version_number: 1.0.0.1
